name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create Google Services JSONs
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
        echo "$GOOGLE_SERVICES" > customer/google-services.json
        echo "$GOOGLE_SERVICES" > partner/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew :customer:assembleDebug :partner:assembleDebug :driver:assembleDebug

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: Bayramenu-APKs
        path: |
          customer/build/outputs/apk/debug/customer-debug.apk
          partner/build/outputs/apk/debug/partner-debug.apk
          driver/build/outputs/apk/debug/driver-debug.apk
